### ISSUE TITLE
Deactivate Login step

### ISSUE THREAD

**Issue by tomcatcw1980** [glenndehaan/unifi-voucher-site#30]
Hi Glenn,

is there a way to skip the login step? I would like to implement the login step via SSO (Authentik). 

Thank you.

**Comment by glenndehaan** [comment]
Hey,

Good news I just finished a new build that should allow this by setting the following environment variable:

```yaml
version: '3'
services:
  app:
    image: glenndehaan/unifi-voucher-site
    environment:
      # Disables the login/authentication for the portal
      DISABLE_AUTH: 'false'
```

Don't forget to pull the latest version of the image before restarting.

Kind regards,
Glenn de Haan
