### ISSUE TITLE
Label Printing

### ISSUE THREAD

**Issue by jlengelbrecht** [glenndehaan/unifi-voucher-site#37]
Hi there. 

Playing around a bit more with this app, and trying to figure out the printer part of the app. 
I went out and purchased the following [80mm receipt printer](https://www.amazon.com/dp/B085L49L7C). 

I didn't see anything in the documentation on how this is supposed to be setup? 
I attempted to pass through the printer into the container, but the app does not seem to be able to see the printer. My plan was to pass this through into the container so mobile users of the app could just press the print button, and the printer that I passed through into the container is able to pick this up. 

Is this not how the printing feature is supposed to work? 
Any guidance you could give me on this would be much appreciated.  

# Docker-Compose.yml
```
version: '3'
services:
  app:
    image: glenndehaan/unifi-voucher-site:latest
    ports:
      - "3003:3000"
    restart: unless-stopped
    devices:
      - "/dev/bus/usb/005/002:/dev/bus/usb/005/002"
    environment:
      UNIFI_IP: 'my-ip'
      UNIFI_PORT: 443
      UNIFI_USERNAME: 'Automationbot'
      UNIFI_PASSWORD: 'my-secret'
      UNIFI_SITE_ID: 'default'
      SECURITY_CODE: 'my-secret'
      DISABLE_AUTH: 'false'
      VOUCHER_TYPES: '1440,0,25000,25000,2048;4320,0,25000,25000,2048;10080,0,25000,25000,2048;'
      VOUCHER_CUSTOM: 'true'
      SERVICE_WEB: 'true'
      SERVICE_API: 'false'
      SMTP_FROM: 'my-gateway-email'
      SMTP_HOST: 'my-smtp'
      SMTP_PORT: '465'
      SMTP_SECURE: 'true'
      SMTP_USERNAME: 'my-gateway-email'
      SMTP_PASSWORD: 'my-secret'
      LOG_LEVEL: 'info'
```
