### ISSUE TITLE
Setting up the QR-Code functionality (Homeassistant Addon)

### ISSUE THREAD

**Issue by 0xvisualiris** [glenndehaan/unifi-voucher-site#56]
### The question

Hello together,
I found this GitHub project and installed the UniFi Voucher Site on my homeassistant as an addon. Everything works really well. But I can't figure it out, how to enable the QR - Code functionality. Maybe I missed it in the docs or something like that. If anyone can help me, would be really nice!

cheers

**Comment by glenndehaan** [comment]
Hi @0xvisualiris,

The QR codes are used within the Email and Print functions (So within the UI they are not displayed). If you have one or both setup but don't see the QR code then you are probably missing:

```yaml
# The UniFi SSID where guests need to connect to (Used within templating and 'Scan to Connect')
UNIFI_SSID: ''
# The UniFi SSID WPA/WPA2/WPA3 Password (Can be ignored for 'Open' networks) (Used within templating and 'Scan to Connect')
UNIFI_SSID_PASSWORD: ''
```

Only the `UNIFI_SSID` is required here if you have an Open network. If not then you also need to assign `UNIFI_SSID_PASSWORD`.

Let me know if this works for you.

Kind regards,
Glenn
